services:
  - type: worker
    name: song-search-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATA_DIR
        value: /data
    disk:
      name: bot-data
      mountPath: /data
      sizeGB: 1
